# Generated by Django 5.0.4 on 2024-04-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='extension',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
