# Generated by Django 5.0.4 on 2024-04-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0002_alter_file_extension_alter_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.FileField(blank=True, upload_to='user_files/'),
        ),
    ]
