# Generated by Django 5.0.4 on 2024-04-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0003_alter_file_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='creator',
            new_name='user',
        ),
    ]
