# Generated by Django 5.0.4 on 2024-04-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0004_rename_creator_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='extension',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(default=''),
        ),
    ]
