# Generated by Django 5.0.4 on 2024-04-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0005_alter_file_extension_alter_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AddField(
            model_name='file',
            name='download_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='handle',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='upload_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='data',
            field=models.FileField(upload_to='user_files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(unique=True),
        ),
    ]
