# Generated by Django 5.0.4 on 2024-04-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0007_alter_file_handle_alter_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='handle',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(null=True, unique=True),
        ),
    ]
