# Generated by Django 5.0.4 on 2024-04-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0008_alter_file_handle_alter_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='extension',
        ),
        migrations.AlterField(
            model_name='file',
            name='download_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
