# Generated by Django 5.0.4 on 2024-04-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0009_remove_file_extension_alter_file_download_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='handle',
        ),
    ]
