# Generated by Django 5.0.4 on 2024-04-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0010_remove_file_handle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='title',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='data',
            new_name='handle',
        ),
    ]
