# Generated by Django 5.0.4 on 2024-04-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0011_rename_title_file_filename_rename_data_file_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(),
        ),
    ]
