# Generated by Django 5.0.4 on 2024-04-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0014_alter_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='handle',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
    ]
