# Generated by Django 5.0.4 on 2024-04-28 02:33

import my_cloud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0016_alter_file_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='handle',
            field=models.FileField(blank=True, null=True, storage=my_cloud.models.UUIDFileStorage('user_files/'), upload_to='user_files/'),
        ),
    ]
