# Generated by Django 5.0.4 on 2024-04-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0020_file_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='upload_at',
        ),
        migrations.AddField(
            model_name='file',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
