# Generated by Django 5.0.4 on 2024-04-28 16:12

import my_cloud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0021_remove_file_upload_at_file_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='handle',
            field=models.FileField(blank=True, max_length=255, null=True, storage=my_cloud.models.UUIDFileStorage(), upload_to=''),
        ),
    ]
