# Generated by Django 5.0.4 on 2024-04-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cloud', '0022_alter_file_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
